---
version: '3.8'

services:
  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    ports:
      - 1883:1883
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "1883" ]
      interval: 15s
      timeout: 5s
      retries: 10

  web-api:
    build: .
    deploy:
      replicas: 1
    command: distributed/api.py
    environment:
      - BROKER_IP=broker
      - BROKER_PORT=1883
      - API_ADMIN_USER=admin
      - API_ADMIN_USER_PASSWORD=admin
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  worker:
    build: .
    deploy:
      replicas: 3
    command: distributed/worker.py
    environment:
      - BROKER_IP=broker
      - BROKER_PORT=1883
    depends_on:
      broker:
        condition: service_healthy
      web-api:
        condition: service_healthy

  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    environment:
      - BLOCKCHAIN_API=http://web-api:8080
    depends_on:
      broker:
        condition: service_healthy
    ports:
      - 8000:8501
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8501/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
