# https://taskfile.dev

version: "3"

tasks:
  up:
    desc: Docker compose up
    cmds:
      - docker compose up -d
    silent: true

  down:
    desc: Docker compose down
    cmds:
      - docker compose down
    silent: true

  build:
    desc: Compose build
    cmds:
      - docker compose build
    silent: true

  reup:
    desc: Down, build, Up
    cmds:
      - task: down
      - task: build
      - task: up
    silent: false

  prune:
    desc: Builder prune
    cmds:
      - docker builder prune
    silent: true
